from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("color", models.CharField(default="#5c6b7a", max_length=20)),
                (
                    "icon",
                    models.CharField(
                        default="ph-list-checks",
                        help_text="Nazwa ikony (np. z biblioteki Phosphor Icons).",
                        max_length=60,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("priority", models.CharField(choices=[("low", "Niski"), ("medium", "Średni"), ("high", "Wysoki")], default="medium", max_length=16)),
                ("accent_color", models.CharField(default="#6c7ae0", max_length=20)),
                ("icon", models.CharField(default="ph-check-circle", max_length=60)),
                ("theme_variant", models.CharField(default="base", help_text="Wariant stylistyczny kafelka (np. pastel, mono, vibrant).", max_length=20)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("repeat_frequency", models.CharField(choices=[("none", "Brak"), ("daily", "Codziennie"), ("weekly", "Co tydzień"), ("monthly", "Co miesiąc")], default="none", max_length=16)),
                ("repeat_interval", models.PositiveIntegerField(default=1)),
                ("repeat_until", models.DateField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="todo.taskgroup")),
            ],
            options={
                "ordering": ["is_completed", "-priority", "position", "-created_at"],
            },
        ),
    ]
# Generated by Django 5.2.8 on 2025-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['is_completed', '-created_at'],
            },
        ),
    ]
