# Generated by Django 5.2.8 on 2025-11-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#5c6b7a', max_length=20)),
                ('icon', models.CharField(default='ph-list-checks', help_text='Nazwa ikony (np. z biblioteki Phosphor Icons).', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-priority', 'position', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='accent_color',
            field=models.CharField(default='#6c7ae0', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='icon',
            field=models.CharField(default='ph-check-circle', max_length=60),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_frequency',
            field=models.CharField(choices=[('none', 'Brak'), ('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='theme_variant',
            field=models.CharField(default='base', help_text='Wariant stylistyczny kafelka (np. pastel, mono, vibrant).', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todo.taskgroup'),
        ),
    ]
